### ISSUE TITLE
logchecker run error

### ISSUE THREAD

**Issue by muyu1232** [OPSnet/Gazelle#104]
Fatal error: Uncaught RuntimeException: sh: 1: chardet: not found in /var/www/vendor/yupmin/php-chardet/src/ChardetCommandRunner.php on line 62
RuntimeException: sh: 1: chardet: not found in /var/www/vendor/yupmin/php-chardet/src/ChardetCommandRunner.php on line 62

Call Stack
--

1 | 0.0000 | 363552 | {main}( ) | .../index.php:0
2 | 0.0001 | 366024 | require( '/var/www/classes/script_start.php' ) | .../index.php:90
3 | 0.0028 | 615464 | require( '/var/www/sections/logchecker/index.php' ) | .../script_start.php:426
4 | 0.0028 | 615872 | require( '/var/www/sections/logchecker/take_test.php' ) | .../index.php:10
5 | 0.0062 | 650688 | Logchecker->new_file( ) | .../take_test.php:31
6 | 0.0062 | 650720 | Yupmin\PHPChardet\Chardet->analyze( ) | .../logchecker.class.php:67
7 | 0.0064 | 721016 | Yupmin\PHPChardet\ChardetCommandRunner->run( ) | .../Chardet.php:14

**Comment by ligh7s** [comment]
Install chardet

**Comment by itismadness** [comment]
You need to install [chardet](https://pypi.org/project/chardet/) to take advantage of the full capacity of the logchecker as while all EAC logs should be UTF-16, in the wild for older EAC logs, people upload a wide number of different encodings and chardet really is the best thing for dealing with that.

812a5ae036a8a752ce03e9577a759f58bc536330 has also made the dependency there a soft one instead of hard so that even if you do not have chardet installed, the logchecker will still "work", though will end up with more garbled EAC logs.
