### ISSUE TITLE
other page will execute the code of index page

### ISSUE THREAD

**Issue by li-fstz** [OPSnet/Gazelle#115]
When I open other page like torrent page, the code in `sections/index/private.php` will execute.
```
if (count($News) > 0 && $LoggedUser['LastReadNews'] != $News[0][0]) {
	$Cache->begin_transaction("user_info_heavy_$UserID");
	$Cache->update_row(false, array('LastReadNews' => $News[0][0]));
	$Cache->commit_transaction(0);
	$DB->query("
		UPDATE users_info
		SET LastReadNews = '".$News[0][0]."'
		WHERE UserID = $UserID");
	$LoggedUser['LastReadNews'] = $News[0][0];
}
```
I add `if ($_SERVER['REQUEST_URI'] === '/index.php')` to solve it,but why?

**Comment by itismadness** [comment]
The way the nginx configuration is setup is that all calls to php scripts (e.g. `torrents.php`) checks first to see if that file exists in `public/` and then if not, actually loads `public/index.php` instead and uses that to service the request. However, the original script name remains and is set by nginx so that we can access it via `$_SERVER['SCRIPT_NAME']`. My guess is that this variable is not being set properly and is just ending up as `index.php` consistently as you go to other pages. To confirm, you should add a `var_dump($_SERVER['SCRIPT_NAME']);` around this line:

https://github.com/OPSnet/Gazelle/blob/3105dd26395b4c248df00889c0b517d9abc29b4e/classes/script_start.php#L399

If that is indeed what's happening, then you will need to fix your web server configuration. We suggest using https://github.com/OPSnet/Gazelle/blob/master/.docker/web/nginx.conf for inspiration on that front (it is what powers our development Gazelle environment).
