### ISSUE TITLE
migration cannot proceed on: debian 10

### ISSUE THREAD

**Issue by ntn888** [OPSnet/Gazelle#166]
when running `vendor/bin/phinx migrate`:

Migration cannot proceed, use the source: /var/www/your_domain/html/db/migrations/20200219075508_drop_secret.php

**Comment by haig233** [comment]
https://github.com/OPSnet/Gazelle/blob/5f9da3a6d0ba6e9fc346783f3d2e40c61dc9701f/db/migrations/20200219075508_drop_secret.php#L16

**Comment by itismadness** [comment]
As stated by @haig233, a number of our migrations check for the existence of the `LOCK_MY_DATABASE` environment variable. This is due to the fact that running this migrations on a production database can take a long while and tie up the database if run while the database is under load.

You can bypass this error by doing `LOCK_MY_DATABASE=1 vendor/bin/phinx migrate` for one-offs or using `export LOCK_MY_DATABASE=1` in some more permanent fashion if you're confident you'll always check all migrations before running it (or only running migrations on an offline site).

**Comment by dannymichel** [comment]
> LOCK_MY_DATABASE=1 vendor/bin/phinx migrate

I got passed that error by using that command but then i got stuck on ``Migration cannot proceed, use the source: db/migrations/20200427085116_index_refactor.php``
