### ISSUE TITLE
mysql problem

### ISSUE THREAD

**Issue by cbtrident** [OPSnet/Gazelle#207]
this is my first time with docker so hope it just me 
but am doing docker compose up in Gazelle
but it failing 
and it in the mysql section
 ✔ Container gazelle-sphinxsearch-1  Created                               0.1s
Attaching to gazelle-memcached-1, gazelle-mysql-1, gazelle-ocelot-1, gazelle-pg-                                  1, gazelle-sphinxsearch-1, gazelle-web-1
gazelle-mysql-1         | Initializing database
gazelle-mysql-1         | mysqld: Can't create/write to file '/var/lib/mysql/is_                                  writable' (OS errno 13 - Permission denied)
gazelle-mysql-1         | 2023-05-09T08:43:09.967459Z 0 [Warning] [MY-011068] [S                                  erver] The syntax '--skip-host-cache' is deprecated and will be removed in a fut                                  ure release. Please use SET GLOBAL host_cache_size=0 instead.
gazelle-mysql-1         | 2023-05-09T08:43:09.967806Z 0 [Warning] [MY-010918] [S                                  erver] 'default_authentication_plugin' is deprecated and will be removed in a fu                                  ture release. Please use authentication_policy instead.
gazelle-mysql-1         | 2023-05-09T08:43:09.967864Z 0 [System] [MY-013169] [Se                                  rver] /usr/sbin/mysqld (mysqld 8.0.32-24) initializing of server in progress as                                   process 14
gazelle-mysql-1         | 2023-05-09T08:43:09.974606Z 0 [ERROR] [MY-010460] [Ser                                  ver] --initialize specified but the data directory exists and is not writable. A                                  borting.
gazelle-mysql-1         | 2023-05-09T08:43:09.974625Z 0 [ERROR] [MY-013236] [Ser                                  ver] The designated data directory /var/lib/mysql/ is unusable. You can remove a                                  ll files that the server added to it.
gazelle-mysql-1         | 2023-05-09T08:43:09.974745Z 0 [ERROR] [MY-010119] [Ser                                  ver] Aborting
gazelle-mysql-1         | 2023-05-09T08:43:09.975083Z 0 [System] [MY-010910] [Se                                  rver] /usr/sbin/mysqld: Shutdown complete (mysqld 8.0.32-24)  Percona Server (GP                                  L), Release 24, Revision e5c6e9d2.

so what am doing wrong and how i fix this
i want to try the newer version of gazelle as the last was a very old version
if you need any more information please say

**Comment by cbtrident** [comment]
ok got it the gazelle-mysql-1 to build had to do chmod 777 in the mysql directory in .docker/data as it using user 1001:1001 when it built.

but right now nothing can connect to it and i can not login in to mysql as it allway saying host is not allowd to connect to this mysql server

so much want to test this but it been a pain
how i fix the mysql so the other part can connect to it  as they all 
gettign this 
gazelle-sphinxsearch-1  | ERROR 1130 (HY000): Host '172.18.0.7' is not allowed to connect to this MySQL server
gazelle-sphinxsearch-1  | Still waiting for MySQL (Count: 980).
gazelle-ocelot-1        | Still waiting for Web (Count: 940).

help please

**Comment by wuubi** [comment]
This isn't related to `chmod`ing the directory, be sure to delete the .docker/data/mysql directory before doing a rebuild.

 ~~There requires some tweaking since there are a handful of ports being used (e.g. I had to switch my ingress 36006)~~

I was very wrong about this. I probably spent an unnecessary hour or two troubleshooting that, don't change your ports, and if it's in use without an existing app on the port your container might be stuck. The ports are set the way they are on purpose (I assume?), but yes I'm getting to the same error @cbtrident is after several hours of troubleshooting. I think the database needs to be created or the root user setup correctly, if you run this on a fresh install you get a message that the root user is created with a blank password.

I've tried running this over the years as the setup has reportedly become "easier" and I've set up some odd docker container configurations before, as well as other web applications since my first attempts. This application is absolute hell to run in development and I can't imagine running it in production.

I've heard of people getting this running, and I was a user back when, but for as perfect it is for UI/UX the opposite is true for devops. I paid a friend who was a bit more experienced with VMs back in 2012 or so who was able to get it to the registration screen, but he also hit a roadblock with the SQL table permissions. 

Sorry for the rant, I plan on doing a deep dive into the code base since that could give me some answers, and the obvious workaround for now is to run it manually. Best of luck to any other attempts and appreciate any insight the maintainers could share.

**Comment by wuubi** [comment]
Fun update: I tried bypassing the phinx migration process because that's throwing all sorts of errors.. I was able to get mysql working by using mariadb instead, but that led to needing to change the collation and.. This nightmare never ends, if anyone has a reproducible image of Gazelle I'd greatly appreciate it! ;D

**Comment by cbtrident** [comment]
i used https://github.com/contropist/Gazelle-OPSnet version is based on a older version and works
i give up on the latest like you got marrrrrrrrrrriadb working but gethtne to take was no go 
the older version just work and am not able to work on a site for what i need.it a sham this branch is not been tested or fixed
or better instruction to help

**Comment by wuubi** [comment]
Thanks for sharing, you could try submitting a diff PR, but it's currently 227 commits ahead and nearly 4000 commits behind this repo so I'm sure it's a bit more than you were expecting. Also noticed it's missing ocelot and postgres so that's concerning unless you're running them separately.

Could you clarify what you mean by "the older version just work and am not able to work on a site for what i need", does that mean it runs but you can't login, or it's missing the functionality I mentioned? Running a postgres container should be self explanatory, but [ocelot's container had an issue too](https://github.com/OPSnet/Ocelot/compare/master...wuubi:Ocelot:patch-2).

**Comment by cbtrident** [comment]
sorry bad spell am dyslexia
what i mean old works but new did not
the 'not' should not be there, it should say am able to work on

**Comment by wuubi** [comment]
Ah, no worries, thanks for clarifying! It's interesting it's running without the ocelot container, but I'm not concerned about the torrent tracking capabilities personally. Glad you got it working, too.

**Comment by cbtrident** [comment]
the ocelot docker was easy
this 
Ocelot
The [ocelot](https://github.com/OPSnet/Ocelot) repository is used to build the Ocelot image. To keep things simple, check out the source in a sibling directory to Gazelle.

$ git clone https://github.com/OPSnet/ocelot
$ cd ocelot
$ docker build . -t ocelot

**Comment by itismadness** [comment]
The original issue was resolved as we've switched to using docker volumes instead of pointing at a directory.
