### ISSUE TITLE
Vulnerabilities in Gazelle and TBDEV.net - acunetix

### ISSUE THREAD

**Issue by SebbaGerra** [OPSnet/Gazelle#61]
Is these vulnerabilities already corrected?

https://www.acunetix.com/blog/news/critical-vulnerabilities-discovered-gazelle-tbdev-net/

**Comment by itismadness** [comment]
These vulnerabilities were corrected in Gazelle by WCD the day after they were originally reported:
https://github.com/WhatCD/Gazelle/commit/133b188d6b68889b6ab17fc54e133fc39ef45a4c

We've also begun (slowly) updating all queries within Gazelle to use prepared queries instead of how they're currently done which will mitigate any such attack vector going forward.

**Comment by SebbaGerra** [comment]
So, for XSS script attack, any change are made?
